"""empty message

Revision ID: 087184a1ca09
Revises: 67bc63af6f7b
Create Date: 2024-03-23 00:16:38.999474

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '087184a1ca09'
down_revision = '67bc63af6f7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('semester',
    sa.Column('semester_name', sa.String(length=100), nullable=False),
    sa.Column('recruitment_started', sa.DateTime(), nullable=True),
    sa.Column('recruitment_end', sa.DateTime(), nullable=True),
    sa.Column('recruitment_status', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('semester_name')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=14), nullable=False),
    sa.Column('semester', sa.String(length=4), nullable=False),
    sa.Column('dob', sa.Date(), nullable=False),
    sa.Column('blood_group', sa.String(length=3), nullable=False),
    sa.Column('department', sa.String(length=35), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.Column('approved', sa.Boolean(), nullable=True),
    sa.Column('designation', sa.String(length=20), nullable=True),
    sa.Column('joined_semester', sa.String(length=10), nullable=False),
    sa.Column('reset_token', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone'),
    sa.UniqueConstraint('reset_token'),
    sa.UniqueConstraint('student_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('semester')
    # ### end Alembic commands ###
