"""Initial migration

Revision ID: 25a4c050a404
Revises: 
Create Date: 2024-03-01 17:41:21.867153

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25a4c050a404'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('semester',
    sa.Column('semester_name', sa.String(length=100), nullable=False),
    sa.Column('recruitment_started', sa.DateTime(), nullable=True),
    sa.Column('recruitment_end', sa.DateTime(), nullable=True),
    sa.Column('recruitment_status', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('semester_name')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('student_id', sa.String(length=10), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=10), nullable=False),
    sa.Column('semester', sa.String(length=10), nullable=False),
    sa.Column('dob', sa.Date(), nullable=False),
    sa.Column('blood_group', sa.String(length=3), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.Column('approved', sa.Boolean(), nullable=True),
    sa.Column('designation', sa.String(length=20), nullable=True),
    sa.Column('joined_semester', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone'),
    sa.UniqueConstraint('student_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('semester')
    # ### end Alembic commands ###
