"""RFID added

Revision ID: 32307c120809
Revises: 9dee45f16fc7
Create Date: 2024-04-14 22:19:44.238735

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32307c120809'
down_revision = '9dee45f16fc7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rfid', sa.String(length=10), nullable=True))
        batch_op.create_unique_constraint(None, ['rfid'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('rfid')

    # ### end Alembic commands ###
