"""Some columns have been changed

Revision ID: 67bc63af6f7b
Revises: 9d8e1b343249
Create Date: 2024-03-23 00:04:17.700789

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '67bc63af6f7b'
down_revision = '9d8e1b343249'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index('email')
        batch_op.drop_index('phone')
        batch_op.drop_index('student_id')

    op.drop_table('user')
    op.drop_table('semester')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('semester',
    sa.Column('semester_name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('recruitment_started', mysql.DATETIME(), nullable=True),
    sa.Column('recruitment_end', mysql.DATETIME(), nullable=True),
    sa.Column('recruitment_status', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('semester_name'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('user',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('student_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('email', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('phone', mysql.VARCHAR(length=14), nullable=False),
    sa.Column('semester', mysql.VARCHAR(length=4), nullable=False),
    sa.Column('dob', sa.DATE(), nullable=False),
    sa.Column('blood_group', mysql.VARCHAR(length=3), nullable=False),
    sa.Column('password', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('approved', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('designation', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('joined_semester', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('department', mysql.VARCHAR(length=35), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index('student_id', ['student_id'], unique=True)
        batch_op.create_index('phone', ['phone'], unique=True)
        batch_op.create_index('email', ['email'], unique=True)

    # ### end Alembic commands ###
