"""empty message

Revision ID: 9ae77c57fede
Revises: 25a4c050a404
Create Date: 2024-03-02 01:24:05.710335

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9ae77c57fede'
down_revision = '25a4c050a404'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('student_id',
               existing_type=mysql.VARCHAR(length=10),
               type_=sa.Integer(),
               existing_nullable=False)
        batch_op.alter_column('phone',
               existing_type=mysql.VARCHAR(length=10),
               type_=sa.String(length=14),
               existing_nullable=False)
        batch_op.alter_column('semester',
               existing_type=mysql.VARCHAR(length=10),
               type_=sa.String(length=4),
               existing_nullable=False)
        batch_op.alter_column('department',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=35),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('department',
               existing_type=sa.String(length=35),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.alter_column('semester',
               existing_type=sa.String(length=4),
               type_=mysql.VARCHAR(length=10),
               existing_nullable=False)
        batch_op.alter_column('phone',
               existing_type=sa.String(length=14),
               type_=mysql.VARCHAR(length=10),
               existing_nullable=False)
        batch_op.alter_column('student_id',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=10),
               existing_nullable=False)

    # ### end Alembic commands ###
