"""empty message

Revision ID: aea7df42f29d
Revises: 559ec8c95a3b
Create Date: 2024-04-19 20:44:18.775253

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aea7df42f29d'
down_revision = '559ec8c95a3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('booked_by', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'user', ['booked_by'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('booked_by')

    # ### end Alembic commands ###
