"""Student ID changed in Attendance database

Revision ID: e4dcbd57c13d
Revises: 795b00a504d0
Create Date: 2024-04-14 23:54:02.861446

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4dcbd57c13d'
down_revision = '795b00a504d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.drop_constraint('attendance_ibfk_2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['student_id'], ['student_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('attendance_ibfk_2', 'user', ['student_id'], ['id'])

    # ### end Alembic commands ###
