"""empty message

Revision ID: fa90e302a189
Revises: 31fbe18884de
Create Date: 2024-04-21 01:50:47.106825

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fa90e302a189'
down_revision = '31fbe18884de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('otp', sa.String(length=6), nullable=True))
        batch_op.alter_column('tfa',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('tfa',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
        batch_op.drop_column('otp')

    # ### end Alembic commands ###
